### PR TITLE
fix search result issue and added random features and fixes

### PR DESCRIPTION
**Pull request by tfsojon**

### CODE REVIEW

**Comment by devopstoday11** [comment]
@tfsojon  please fix the conflicts with my main branch and re-submit the PR.

**Comment by devopstoday11** [comment]
@tfsojon 
Is there a reason why you removed Changelog? Just asking.

**Comment by devopstoday11** [comment]
@tfsojon 

When I click on changelog button, I am seeing two buttons for changelog when the page loaded. PFA screenshot. 
image

**Comment by devopstoday11** [comment]
@tfsojon 
recorded few more issues here,
https://www.loom.com/share/a4f3466a19264ad393dc6bab404c3de8

**Comment by tfsojon** [comment]
@devopstoday11  - This PR ready to merge now
image

**Pull request merged**
